name: Deploy preview

env:
  PREVIEW_ACCOUNT_ID: 09e1897acd19314fc6df7d21108729b0

on:
  pull_request:
    branches:
      - production
      - main
    types: [labeled, opened, synchronize]

jobs:
  preview:
    name: "Check for preview label"
    outputs:
      result: ${{ steps.step1.outputs.result }}
    runs-on: ubuntu-latest
    steps:
      - name: Set env variable to true when label is present
        id: step1
        if: ${{ contains( github.event.pull_request.labels.*.name, 'preview' ) }}
        run: echo "::set-output name=result::true"

  changes:
    name: "Check for docs changes"
    needs: preview
    if: ${{ needs.preview.outputs.result == 'true' }}
    runs-on: ubuntu-latest
    outputs:
      rules: ${{ steps.filter.outputs.rules }}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2.4.2
        id: filter
        with:
          filters: |
            rules:
              - 'products/rules/**'

  deploy-rules:
    runs-on: ubuntu-latest
    needs: [preview, changes]
    if: ${{ needs.preview.outputs.result == 'true' && needs.changes.outputs.rules == 'true' }}
    defaults:
      run:
        shell: bash
        working-directory: products/rules
    steps:
      - name: Checkout docs
        uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 14.2.0
      - name: Build docs
        run: |
          echo Placeholder
          # npm install
          # mkdir .docs
          # npm run ghactionsbootstrap
          # npm run build
        env:
          WORKERS_ENV: development
      - name: Set up preview config
        run: |
          # chmod o+x ../../.github/setup_preview.sh
          ../../.github/setup_preview.sh ${{ github.event.number }} $PREVIEW_ACCOUNT_ID
        env:
          PREVIEW_ACCOUNT_ID: ${{ env.PREVIEW_ACCOUNT_ID }}
      #- name: Publish preview
      #  uses: cloudflare/wrangler-action@1.2.0
      #  with:
      #    apiToken: ${{ secrets.CF_API_TOKEN }}
      #    workingDirectory: "products/rules"
      #    environment: "preview"

#  add-comment:
#    needs: preview
#    if: ${{ needs.preview.outputs.result == 'true' }}
#    runs-on: ubuntu-latest
#    permissions:
#      issues: write
#    steps:
#      - name: Add comment
#        uses: peter-evans/create-or-update-comment@v1
#        with:
#          issue-number: ${{ github.event.issue.number }}
#          body: |
#            This issue is available for anyone to work on. **Make sure to reference this issue in your pull request.** :sparkles: Thank you for your contribution! :sparkles: